server:
  port: 8080
  forward-headers-strategy: framework
  shutdown: graceful

spring:
  cache:
    caffeine:
      spec: initialCapacity=100,maximumSize=1000,expireAfterAccess=30m
  jpa:
    open-in-view: false
  datasource:
    url: jdbc:h2:mem:post-db
    driver-class-name: org.h2.Driver
    username: sa
    password: password

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  tracing:
    sampling:
      probability: 1.0
  observations:
    key-values:
      application: ${spring.application.name}

loki:
  url: http://localhost:3100/loki/api/v1/push
