spring:
  application:
    name: photo-service
  jpa:
    open-in-view: false
  datasource:
    url: jdbc:h2:mem:photo-db
    driver-class-name: org.h2.Driver
    username: sa
    password: password

server:
  port: 8083