spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service
            uri: lb://USER-SERVICE
            predicates:
              - Path=/users/**
            filters:
              - RewritePath=/(?<segment>.*),/api/v1/${segment}
          - id: post-service
            uri: lb://POST-SERVICE
            predicates:
              - Path=/posts/**
            filters:
              - RewritePath=/(?<segment>.*),/api/v1/${segment}
          - id: comment-service
            uri: lb://COMMENT-SERVICE
            predicates:
              - Path=/comments/**
            filters:
              - RewritePath=/(?<segment>.*),/api/v1/${segment}
          - id: album-service
            uri: lb://ALBUM-SERVICE
            predicates:
              - Path=/albums/**
            filters:
              - RewritePath=/(?<segment>.*),/api/v1/${segment}
          - id: photo-service
            uri: lb://PHOTO-SERVICE
            predicates:
              - Path=/photos/**
            filters:
              - RewritePath=/(?<segment>.*),/api/v1/${segment}
          - id: todo-service
            uri: lb://TODO-SERVICE
            predicates:
              - Path=/todos/**
            filters:
              - RewritePath=/(?<segment>.*),/api/v1/${segment}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8090



