spring:
  application:
    name: post-service
  jpa:
    open-in-view: false
  datasource:
    url: jdbc:h2:mem:post-db
    driver-class-name: org.h2.Driver
    username: sa
    password: password

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


server:
  port: 8080