management:
  zipkin:
    tracing:
      endpoint: http://tempo:9411/api/v2/spans

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka

loki:
  url: http://loki:3100/loki/api/v1/push
