spring:
  application:
    name: user-service
  jpa:
    open-in-view: false
  datasource:
    url: jdbc:h2:mem:user-db
    driver-class-name: org.h2.Driver
    username: sa
    password: password

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8085