eureka:
  server:
    wait-time-in-ms-when-sync-empty: 0
  instance:
    hostname: service-registry
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/