spring:
  jpa:
    open-in-view: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  tracing:
    sampling:
      probability: 1.0
